dist: xenial
language: python
python:
  - "3.7"
services:
  - docker

install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile --deploy --system
  - docker build . --tag test-autowebcompat
script:
  - flake8 .
  - pytest ./tests/test_*.py --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
