# Generated by Django 2.2.1 on 2019-05-04 23:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_started_at', models.DateTimeField()),
                ('training_ended_at', models.DateTimeField(null=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_model', models.CharField(choices=[('vgg16', 'vgg16'), ('vgg19', 'vgg19'), ('inception', 'inception'), ('vgglike', 'vgglike'), ('simnet', 'simnet'), ('simnetlike', 'simnetlike'), ('resnet50', 'resnet50')], default='vgg16', max_length=256)),
                ('optimizer', models.CharField(choices=[('sgd', 'Stochastic Gradient Descent (sgd)'), ('adam', 'Adam (adam)'), ('nadam', 'Nesterov Adam (nadam)'), ('rms', 'RMSProp (rms)')], default='sgd', max_length=256)),
                ('classification_type', models.CharField(choices=[('Y vs D + N', 'detect content differences as errors (y vs d + n)'), ('Y + D vs N', 'ignore content differences (y + d vs n)')], default='Y vs D + N', max_length=256)),
                ('early_stopping', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, default='', max_length=4096)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField()),
                ('original_id', models.IntegerField(default=None, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('png', models.BinaryField(max_length=8388608)),
                ('filename', models.CharField(max_length=256)),
                ('browser_name', models.CharField(max_length=128)),
                ('browser_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sequence')),
            ],
            options={
                'unique_together': {('sequence', 'filename', 'browser_name')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=1)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Decision')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='network',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NetworkTemplate'),
        ),
        migrations.AddField(
            model_name='decision',
            name='pic_left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_left', to='app.Screenshot'),
        ),
        migrations.AddField(
            model_name='decision',
            name='pic_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_right', to='app.Screenshot'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('y', 'compatible (y)'), ('n', 'not compatible (n)'), ('d', 'content differences (d)')], max_length=1)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Decision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('decision', 'user')},
            },
        ),
    ]
